### ISSUE TITLE
Leaderboard addresses should show full address on hover

### ISSUE THREAD

**Issue by Klapeyron** [bigshortbets/market-frontend#107]
**Is your feature request related to a problem? Please describe.**
It is not possible to recover user address on the leaderboard

**Describe the solution you'd like**
There should be at least some information for 'mouseover'

**Describe alternatives you've considered**

**Additional context**

**Comment by kacpergumieniuk** [comment]
I'm providing new solution for that case, we will provide copy button which will copy address to the clipboard
