### ISSUE TITLE
Fix sending of transactions to wrong network after manually changing it in wallet

### ISSUE THREAD

**Issue by Klapeyron** [bigshortbets/market-frontend#14]
It is possible to send transactions on the wrong network like ethereum mainnet:
https://etherscan.io/tx/0xa94092adc17cf31205f622c513aaf8c244324fd1742d3fe04cba395a2294c2f4

Steps to reproduce:
1) Enter frontendapp
2) Change manually network in Metamask to Ethereum mainnet
3) Place order on any market

At this moment, we are signing transaction that will be sent to Ethereum mainnet, not out chain.

**Comment by kacpergumieniuk** [comment]
Fixed possibility to send tx from other chains that ours
