### ISSUE TITLE
Implement Oracle Price column in Positions tab

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#168]
Following common practices on trading platforms, adding the Oracle Price between the Entry Price and Unrealized PnL in the Positions tab, would enhance user experience by providing valuable reference data for positions.

Visual example:
![ScreenShot 11 09 24 at 00-47-28](https://github.com/user-attachments/assets/37477f82-fd76-4160-8c96-51178f3fe31c)

**Comment by kacpergumieniuk** [comment]
will do it for aggregated for now
