### ISSUE TITLE
Numbers should be correctly formatted

### ISSUE THREAD

**Issue by Klapeyron** [bigshortbets/market-frontend#19]
![Image](https://github.com/bigshortbets/market-frontend/assets/11329616/bbc6c423-cc64-4b69-b4d6-99a5c1d3bc40)
![Image](https://github.com/bigshortbets/market-frontend/assets/11329616/b99242eb-b134-4854-8879-7d866d85b5d1)

**Comment by kacpergumieniuk** [comment]
Fixed
