### ISSUE TITLE
Typo in Market Status and Positions tab: "Everything fine"

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#23]
The text 'Everything fine' is not grammatically correct in English. The correct version would be 'Everything is fine'. Alternatively, 'Everything's fine' or 'Status: OK'.

The typo occurs in two places: in the Positions tab when there is at least one open position, and in the footer of the main panel.

![typo eve](https://github.com/bigshortbets/market-frontend/assets/106878771/534ee807-befc-4470-8d4e-339421ff1cfc)

**Comment by DanDanielD** [comment]
Another, third instance of the 'everything fine' typo is in the Deposit tab in the Market panel:

![typo2](https://github.com/bigshortbets/market-frontend/assets/106878771/ea558261-a3bd-425b-8d15-b998177cf095)

**Comment by DanDanielD** [comment]
Two additional instances of the 'Everything fine' typo are visible in **Deposit tab** when wallet is **not connected**:
![typo4](https://github.com/bigshortbets/market-frontend/assets/106878771/97a6c214-3fcd-45cc-b64f-662c121ee8ab)
![everything fine not connected](https://github.com/bigshortbets/market-frontend/assets/106878771/95306e9c-4aff-40a9-a9cb-e5e343f6cfe6)

**Comment by kacpergumieniuk** [comment]
@DanDanielD thanks, will change frontend's representation to Everything's fine
