### ISSUE TITLE
 Help Text in the Deposit tab is irrelevant in this context when wallet not connected

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#25]
Help Text in the Deposit tab is irrelevant in this context when wallet not connected.

For consistency, it may be beneficial to display the same "Connect your wallet to interact with the market" notification across all tabs (order, deposit, withdraw, bridge), or alternatively, not display it at all.

Deposit, Order and Withdraw tabs when wallet not connected: 
![irrelevant help](https://github.com/bigshortbets/market-frontend/assets/106878771/483fa5cb-1c09-484a-8540-57ea9eb8fda3)![image_2024-03-23_221039207](https://github.com/bigshortbets/market-frontend/assets/106878771/b10c9634-77b9-4158-a7d5-a98d36e98dea)
![image_2024-03-23_221052718](https://github.com/bigshortbets/market-frontend/assets/106878771/1da6cb3e-bf27-4cd1-afaf-01482294ddc1)

**Comment by kacpergumieniuk** [comment]
Thanks, i've made sure that blue info is only displaying when user is connected, and provided conect wallet warnings for withdraw and deposit.
