### ISSUE TITLE
Inconsistent and unclear date formatting in Contract Details

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#30]
The date formatting in the Market Duration field, within Contract Details (currently displayed as dd.mm.yyyy) is inconsistent with the widely used ISO 8601 date formatting (yyyy-mm-dd) applied in the History tab. 

Additionally, the format dd.mm.yyyy may be misinterpreted, especially in regions following the mm/dd/yyyy convention such as the US. For example, a date like 03.05.2025 could be mistakenly interpreted as March 5th or May 3rd.

I suggest either aligning the format with that used in the History tab or ensuring complete clarity by using date formatting with three-letter month codes, such as 31 Jan 2024 - 20 Mar 2024.

![market duration dates](https://github.com/bigshortbets/market-frontend/assets/106878771/3eb5be1a-36db-497d-89fa-59e5894277cd)

Attaching a screenshot of the History Tab for reference. The issue with visible below date representation has been reported 
[here.](https://github.com/bigshortbets/market-frontend/issues/26#issue-2204405500)
![image](https://github.com/bigshortbets/market-frontend/assets/106878771/8eda2746-b054-4dec-9779-6664d6874abe)

**Comment by Klapeyron** [comment]
I vote for 31 Jan 2024 - 20 Mar 2024 in Contract details

**Comment by kacpergumieniuk** [comment]
Changed representation to dd MMM yyyy
