### ISSUE TITLE
 Inaccurate Labeling: "Possible withdraw" instead of "Available for withdrawal"

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#31]
The current label "Possible withdraw" in the Withdraw tab is not ideal.
Established financial applications typically use clearer terms like "Available:", "Available balance:" or "Available for withdrawal:".
Personally, I would recommend using 'Available for withdrawal:' as it provides the clearest and most informative label for users in this context.

![available for withdrawal](https://github.com/bigshortbets/market-frontend/assets/106878771/9cf9eee8-91fd-4e20-9dd6-1f99c9040679)

**Comment by kacpergumieniuk** [comment]
Changed, thanks
