### ISSUE TITLE
The bottom navigation panel is not visible on mobile devices after the page loads

### ISSUE THREAD

**Issue by Klapeyron** [bigshortbets/market-frontend#33]
Should be with panel:
![Screenshot_20240403-093924](https://github.com/bigshortbets/market-frontend/assets/11329616/11ba3e1a-cc74-430e-a715-499c45ada128)

Now we have:
![Screenshot_20240403-093935](https://github.com/bigshortbets/market-frontend/assets/11329616/75a91ee9-7c7a-4d4b-9254-adc260ac82bf)

**Comment by kacpergumieniuk** [comment]
done 
![image](https://github.com/bigshortbets/market-frontend/assets/48014664/73bd20cb-04d7-4c6e-8809-3ea3612cead4)

**Comment by Klapeyron** [comment]
![IMG_0061](https://github.com/bigshortbets/market-frontend/assets/11329616/7291a1cd-f961-4d63-86b3-fb5969c00dc5)
