### ISSUE TITLE
Add links to orders that forwarding to polkadot explorer

### ISSUE THREAD

**Issue by Klapeyron** [bigshortbets/market-frontend#36]
Each order creation is associated with a block number (available in graphql). Would be great to have an option to jump from order to explorer and show associated transaction
[sample URL](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftest-market.bigsb.network#/explorer/query/0x10ed610e6b94c7dd5eec59e945ef87c7d6468de2c3280b51a6a67547a53e1a5d)

**Comment by kacpergumieniuk** [comment]
@Klapeyron

**Comment by Klapeyron** [comment]
Sample with order:
```json
      {
        "blockHeight": "1059433",
        "id": "13835058055282165321"
      }
```
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftest-market.bigsb.network#/explorer/query/1059433

**Comment by Klapeyron** [comment]
@autopilot
