### ISSUE TITLE
Deposits/Balance Panel disappears when desktop browser window is narrowed

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#40]
The Deposits/Balance Panel (marked in the first screenshot) disappears when the desktop browser window is narrowed beyond a certain width, making Wallet Balance, Total Deposits, Market Deposit, and Status information inaccessible.

Steps to reproduce:
1. Open https://test-market.bigsb.io/ in a web browser.
2. Gradually resize the browser window horizontally.

Bug occurs on following setups:
Win10/Opera 108, Win10/Chrome 123, Win7/Opera 95

![disappearing panel](https://github.com/bigshortbets/market-frontend/assets/106878771/17edeb0c-168b-44f4-8260-61af28789a81)

Narrow browser window:

![ScreenShot 11 04 24 at 15-51-11](https://github.com/bigshortbets/market-frontend/assets/106878771/52eb249a-798c-4b8f-a8cc-2e45d3d23c6c)

**Comment by kacpergumieniuk** [comment]
done 
![image](https://github.com/bigshortbets/market-frontend/assets/48014664/9657eb8e-9f89-44ff-9536-52e395aba441)
