### ISSUE TITLE
 Deposits/Balance Panel missing on mobile devices

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#41]
The Deposits/Balance Panel (marked in the first screenshot - desktop web browser view) is not visible on mobile devices. As a result, Wallet Balance, Total Deposits, Market Deposit, and Status information are inaccessible.

Steps to reproduce:
Open https://test-market.bigsb.io/ on a mobile device.

Reproducible on:
Android 9 / Chrome 123
Android 9 / Firefox 124
Android 13 / Samsung Internet 24

Desktop browser view with marked panel:

![ScreenShot 11 04 24 at 15-01-42](https://github.com/bigshortbets/market-frontend/assets/106878771/8c3f658c-6e53-4cae-844e-13623fa015fa)

Mobile browser view:

![image](https://github.com/bigshortbets/market-frontend/assets/106878771/6b4fddf3-abf5-45bc-b7db-1130eb9fc992)

**Comment by kacpergumieniuk** [comment]
done 
![image](https://github.com/bigshortbets/market-frontend/assets/48014664/313639b6-67fe-43e2-9f16-edccc2907feb)
