### ISSUE TITLE
The name of the asset is not shown in the order table

### ISSUE THREAD

**Issue by B3fromSuffering** [bigshortbets/market-frontend#61]
In "Orders" and "History" tabs the asset name column is missing. 
This should be visible at first glance to improve the user experience
<img width="386" alt="asset name" src="https://github.com/bigshortbets/market-frontend/assets/58731236/f0bba31a-7e7a-429e-b48f-ff524ab56aad">

**Comment by DanDanielD** [comment]
ds

**Comment by DanDanielD** [comment]
I have verified the issue and confirmed that it has been resolved. The ticket is now ready to be closed.
![image](https://github.com/bigshortbets/market-frontend/assets/106878771/68e827a3-a976-4770-ae45-4e2499908b34)
