### ISSUE TITLE
Counter in Orders and Positions tab header is not reflecting actual value unless clicked

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#65]
The order counter displayed in the header of the Orders tab, marked on the screenshot below, is inaccurate and does not show the correct number of orders unless clicked. 

After logging in, refreshing the page, or placing an order, the counter remains at 0 despite active orders existing. Clicking on the Orders tab triggers the counter to update and display the correct value.

**Expected behavior:**
The order counter displayed in the Orders tab header should reflect the current number of active orders. This includes updates triggered by: logging in, page refresh, and any action that affects the order list (e.g., placing an order, canceling an order).

**Steps to reproduce:**
1. Login to the market app by connecting your wallet.
2. Place an order on any market. Observe the counter in the Orders header that does not update and shows 0 despite the order being placed.
3. Click on the Orders tab. The counter should update to reflect the newly placed order (1).
4. Refresh the website. Observe that the counter displays 0.
5. Log out and then log back in. Observe that the counter again displays 0.
6. Click on the Orders tab. The counter should update to show the open order (1).

 
**Reproducible on:**
Win10/Opera109
win10/Chrome124
Android9/Chrome123
 
![image_2024-04-16_195942733](https://github.com/bigshortbets/market-frontend/assets/106878771/b1685ffe-4f68-477c-89cc-b2ff398ca5cc)

**Comment by kacpergumieniuk** [comment]
done
