### ISSUE TITLE
Inaccurate terminology: "Indexes" instead of "Indicies"

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#66]
The term "Indices" is the more commonly used term in the financial industry to refer to a collection of index instruments.

![image_2024-04-16_214500194](https://github.com/bigshortbets/market-frontend/assets/106878771/4140678a-e103-48b6-be58-0c01b4c4b049)

**Comment by kacpergumieniuk** [comment]
Thanks for pointing that out @DanDanielD , fixed.
