### ISSUE TITLE
Markets in Market List are not in alphabetical order

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#67]
When the Market List is expanded, markets appear in non-alphabetical order within their groups, regardless of the selected group - Commodities, All, Crypto, etc. This makes navigating and finding specific markets challenging, especially for large groups.

![image](https://github.com/bigshortbets/market-frontend/assets/106878771/6b4aaba3-3199-4947-acb1-3f2633ab17dc)

**Comment by Klapeyron** [comment]
Associated with https://github.com/bigshortbets/market-frontend/issues/68

**Comment by kacpergumieniuk** [comment]
Closed with #68
