### ISSUE TITLE
 Market List order changes dynamically without user interaction

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#68]
The order of markets in the Market List dynamically changes without user interaction when the list is expanded and the "All" group is selected. These changes occur at irregular intervals, observed to happen every 15 seconds, followed by 3 seconds, and then 6 seconds (and potentially other inconsistent intervals).

**Expected Behavior:**
The Market List order should consistently remain alphabetical regardless of the selected group.

**Related Issue:**
#67 Markets in Market List are not in alphabetical order

**Steps to Reproduce:**

1. Navigate to https://test-market.bigsb.io/
2. Click the currently active market to expand the Market List.
3. Select the "All" group to view all available markets.
4. Observe the dynamic reordering of the list within 30 seconds of choosing "All".

**Reproducible on:**

Win10/Opera 123
Win10/Chrome 124
Android 9/Chrome 123
![ezgif-3-30d0e6965d](https://github.com/bigshortbets/market-frontend/assets/106878771/00a538a4-9dd4-4a99-bb88-21c1043c6ade)

**Comment by kacpergumieniuk** [comment]
Now markets are sorted alphabetically @DanDanielD im closing this issue.
