### ISSUE TITLE
Refinement of statement about DOLAR$ currency

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#78]
Refinement of the legal disclaimer regarding the DOLAR$ currency.
Refined statement:
`
DOLAR$ is virtual sandbox currency and has no real settlement value like 'fake money'. It's an internal part of the software and can't be used for billing.
`

![image](https://github.com/bigshortbets/market-frontend/assets/106878771/3df0b3f3-2150-4c3c-9d40-0198538ae662)

**Comment by kacpergumieniuk** [comment]
@DanDanielD we don't want to refer to any financial asset like currency , etc.

**Comment by kacpergumieniuk** [comment]
If you have any other proposals, feel free to write it here
