### ISSUE TITLE
 Misaligned positions Status in positions list

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#79]
The Status within the Positions list is horizontally misaligned. The text for some positions appears slightly shifted to the left or right compared to others. It seems their position is determined relative to the PNL amount (Dolar$).

![image](https://github.com/bigshortbets/market-frontend/assets/106878771/a7c4e507-5a0a-4ec1-8be4-df55063e7d98)

**Comment by kacpergumieniuk** [comment]
Done
