### ISSUE TITLE
Link Market Logo/Name to Main Market Page

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#88]
The market logo/name in the top left corner should be clickable and lead to the main market page for easy navigation, especially as additional pages are introduced in the future. 
Ideally, the entire area marked in the screenshot should be clickable.

![image](https://github.com/bigshortbets/market-frontend/assets/106878771/6e36ac89-6610-48be-94c0-49e9476f8c1b)

**Comment by kacpergumieniuk** [comment]
will do that when we got more then one route in our app , so w the leaderboard, now its useless when we're in the scope of only one route

**Comment by kacpergumieniuk** [comment]
nvm, its already works that way, closing
