### ISSUE TITLE
Rename "Total Deposits" to "Used Balance" and "Market Deposit" to "Market Margin"

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#90]
Following the agreed logic for displaying fund structure on the market, the following changes are required:

-Rename "Total Deposits" to "Used Balance".
-Rename "Market Deposit" to "Market Margin".

As per the planned design, Used Balance will display the sum of the following amounts:
-All initial margins currently reserved for open orders
-All initial margins of open positions
-All market margins
Market Deposit will be renamed to Market Margin for better clarity.

Screenshot of the expected result:
![ScreenShot 31 05 24 at 18-05-10](https://github.com/bigshortbets/market-frontend/assets/106878771/bf730368-8e73-4e6a-9fb9-e2a7921509ed)

**Comment by Klapeyron** [comment]
Depends on: https://github.com/bigshortbets/indexer/issues/69

**Comment by Klapeyron** [comment]
@autopilot

**Comment by Klapeyron** [comment]
@autopilot

**Comment by Klapeyron** [comment]
@autopilot solve this issue

**Comment by Klapeyron** [comment]
@autopilot

**Comment by Klapeyron** [comment]
@autopilot create pull request solving this issue

**Comment by Klapeyron** [comment]
@autopilot propose code solution

**Comment by Klapeyron** [comment]
@autopilot dependency is resolved

**Comment by Klapeyron** [comment]
Associated with: https://github.com/bigshortbets/market-frontend/issues/93

**Comment by DanDanielD** [comment]
We have revised the design and will now display three elements: Account Balance, Available Balance, and Market Margin (which will remain unchanged).

- **Account Balance** will represent the sum of:
   - Unrealized PnL with non-collectible profits deducted
   - Available Balance
   - The former 'Total Margin,' representing the sum of margins across all markets
   - Initial margins reserved for open orders

- **Available Balance** will represent the user's accessible funds."**

![image](https://github.com/user-attachments/assets/60c6926d-636a-4d00-b86f-5916b03d6457)

**Comment by Klapeyron** [comment]
Depends on: https://github.com/bigshortbets/market-frontend/issues/96
