### ISSUE TITLE
Create Close Order window - text and layout changes

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#92]
Minor changes are required in the Create Close Order window to adhere to industry standards.

1. Change "Create Close Order" to "Create Closing Order" in the title bar and the button for better precision and common usage.

2. Change "Position profit/loss" to "Position Profit/Loss" for consistency.

3. Move the "Position Profit/Loss" line to the bottom of the window to maintain logical order.

Screenshot for reference:
![ScreenShot 02 06 24 at 00-22-04](https://github.com/bigshortbets/market-frontend/assets/106878771/d612f797-239a-447f-9584-ea5e35d4202e)

**Comment by kacpergumieniuk** [comment]
Done
