### ISSUE TITLE
Funds not returning to Wallet Balance after closing Position

### ISSUE THREAD

**Issue by DanDanielD** [bigshortbets/market-frontend#98]
When placing an order, funds are taken from the Wallet Balance and reserved. When the open order is matched and the position is opened, the funds (initial margin) are moved to Market Margin. After closing the position, the funds remain in Market Margin and do not return to the Wallet Balance, causing depletion of funds in the Wallet Balance over time, which prevents placing new Open Orders. 

The solution is to automatically transfer part of the funds from Market Margin back to Wallet Balance, as discussed during our Zoom call.

**Comment by kacpergumieniuk** [comment]
thats not frontend logic @DanDanielD

**Comment by DanDanielD** [comment]
@Klapeyron Could you please take a look at this?
